<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: escovan
 * Date: Wed, 01 Jun 2016 09:14:40 +0000
 */

$conf['title'] = 'Logboeken, Documenten & Wiki';
$conf['lang'] = 'nl';
$conf['license'] = 'cc-by-nc';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['subscribers'] = 1;
$conf['proxy']['user'] = 'escovan';
$conf['proxy']['pass'] = '<b>VGlyc2llMTk4OTAk';

// end auto-generated content
